services:
    app.manager.abstract:
        class: AppBundle\Manager\AbstractManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_paginator"
            - "@request_stack"

    app.manager.contact:
        class: AppBundle\Manager\ContactManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_paginator"
            - "@request_stack"

    app.manager.job:
        class: AppBundle\Manager\JobManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_paginator"
            - "@request_stack"

    app.manager.city:
        class: AppBundle\Manager\CityManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_paginator"
            - "@request_stack"

    app.manager.tag:
        class: AppBundle\Manager\TagManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_paginator"
            - "@request_stack"

    app.manager.friend:
        class: AppBundle\Manager\FriendManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_paginator"
            - "@request_stack"

    app.manager.user:
        class: AppBundle\Manager\UserManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_paginator"
            - "@request_stack"
            - "@fos_user.user_manager.default"
            - "@security.authorization_checker"