app:
    resource: "@AppBundle/Controller"
    type:     annotation
    prefix:   /

web_service:
    resource: "@AppBundle/Controller/WebService"
    type:     annotation
    prefix:   /service-web

admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
